version: '3'
services:
  gateway-service:
    image: gateway-service
    build:
      context: .
      dockerfile: Dockerfile_gateway-service
    container_name: gateway-service
    hostname: gateway-service
    ports:
      - "8083:8083"
    networks: 
      customnetwork: 
        ipv4_address: 172.40.0.10  
    restart: unless-stopped
    logging:
      options:
        max-size: 50m
        max-file: "10"
        compress: "true"
    volumes:
      - ./service/gateway-service/config:/micro-service/service/gateway-service/config/
    environment:
      - TZ=Asia/Ho_Chi_Minh            
  collector:
    image: otel/opentelemetry-collector:0.72.0
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-config/otel-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
    depends_on:
      - jaeger-service

  jaeger-service:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14250"      
networks:
  core_netword: 
    ipam:
      config: 
        - subnet: 172.40.0.0/16
      
        
