version: '3'
services:
  gateway-service:
    image: gateway-service
    build:
      context: .
      dockerfile: Dockerfile_gateway-service
    container_name: gateway-service
    hostname: gateway-service
    ports:
      - "8083:8083"
    networks: 
      customnetwork: 
        ipv4_address: 172.20.0.10  
    restart: unless-stopped
    logging:
      options:
        max-size: 50m
        max-file: "10"
        compress: "true"
    volumes:
      - ./service/gateway-service/config:/micro-service/service/gateway-service/config/
    environment:
      - TZ=Asia/Ho_Chi_Minh
  gateway-service_1:
    image: gateway-service_1
    build:
      context: .
      dockerfile: Dockerfile_gateway-service
    container_name: gateway-service_1
    hostname: gateway-service
    ports:
      - "8085:8083"
    networks: 
      customnetwork: 
        ipv4_address: 172.20.0.13  
    restart: unless-stopped
    logging:
      options:
        max-size: 50m
        max-file: "10"
        compress: "true"
    volumes:
      - ./service/gateway-service/config:/micro-service/service/gateway-service/config/
    environment:
      - TZ=Asia/Ho_Chi_Minh
  gateway-service_2:
    image: gateway-service_2
    build:
      context: .
      dockerfile: Dockerfile_gateway-service
    container_name: gateway-service_2
    hostname: gateway-service
    ports:
      - "8086:8083"
    networks: 
      customnetwork: 
        ipv4_address: 172.20.0.14  
    restart: unless-stopped
    logging:
      options:
        max-size: 50m
        max-file: "10"
        compress: "true"
    volumes:
      - ./service/gateway-service/config:/micro-service/service/gateway-service/config/
    environment:
      - TZ=Asia/Ho_Chi_Minh            
  authen-service:
    image: authen-service
    build: 
      context: .
      dockerfile: Dockerfile_authen-service
    container_name: authen-service
    hostname: authen-service
    ports:
      - "9999:9999"
    networks: 
      customnetwork: 
        ipv4_address: 172.20.0.11      
    restart: unless-stopped
    logging:
      options :  
        max-size: 50m
        max-file: "10"
        compress: "true"  
    volumes:
      - ./service/authen-service/config:/micro-service/service/authen-service/config/  
    environment:
      - TZ=Asia/Ho_Chi_Minh                       
  other-service:
    image: other-service
    build: 
      context: .
      dockerfile: Dockerfile_other-service
    container_name: other-service
    hostname: other-service
    ports:
      - "8888:8888"
    networks: 
      customnetwork: 
        ipv4_address: 172.20.0.12        
    restart: unless-stopped
    logging:
      options :  
        max-size: 50m
        max-file: "10"
        compress: "true"  
    volumes:
      - ./service/other-service/config:/micro-service/service/other-service/config/  
    environment:
      - TZ=Asia/Ho_Chi_Minh
  ngin-x:
    image: ngin-x
    build:
      context: .
      dockerfile: Dockerfile_nginx
    container_name: ngin-x
    ports:
      - "80:80"
    networks: 
      customnetwork: 
        ipv4_address: 172.20.0.20                                         
networks:
  customnetwork: 
    ipam:
      config: 
        - subnet: 172.20.0.0/16
      
